### ISSUE TITLE
Hacktoberfest: Text search over plants demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-text-search-plants#1]
This is the tracker for polishing the “Text search over plants” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Fixes for any of the identified issues 
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [ ] Including used Weaviate modules/ML models
    - [x]  demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [ ] Add progress bar to import file (add_data.js)
    - [ ] Add ‘nearObject’ type searches to recommend similar plants to a selected plant
    - [ ] Add generative search to do something like descriptions of plants. Alternatively, generate plant descriptions in a [generative feedback loop](https://weaviate.io/blog/generative-feedback-loops-with-llms)
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point) (claimed by @Ahsankhalid618)
    - [ ] Optional: Conversion to Python (claimed by @someshfengde)
        - [ ] Optional: Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
            - [ ] After Weaviate release 1.22: swap out preview image

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by syed-muheed** [comment]
I am ready to work on it please assign this to me

**Comment by iamleonie** [comment]
@syed-muheed Thank you for volunteering. As multiple people can contribute to this issue, I will not assign anyone to it. 
Please let me and others know which parts of the issue you would like to contribute to.

Please note that we will announce and start our Hacktoberfest activities on Monday, October 2nd, with an official announcement and instructions.

**Comment by VishalPraneeth** [comment]
Hey @iamleonie, I've contributed the pre-requisites and Usage instructions part.

**Comment by iamleonie** [comment]
@VishalPraneeth That's awesome. Thank you for your contribution. Please don't hesitate to ping us in Slack or our forum if you need assistance opening the pull request.

**Comment by VishalPraneeth** [comment]
> @VishalPraneeth That's awesome. Thank you for your contribution. Please don't hesitate to ping us in Slack or our forum if you need assistance opening the pull request.

Can you please review the PR

**Comment by iamleonie** [comment]
@VishalPraneeth Thank you for your contribution! It was merged just now!

**Comment by VishalPraneeth** [comment]
Hey @iamleonie , Created another PR for Description of the project and technologies used!

**Comment by iamleonie** [comment]
I wanted to quickly get an overview of who is working on what at the moment.

Hey @syed-muheed, could you please let me know if you are currently working on this and if yes, which parts?

If anyone else is currently working on this, please leave a comment here what you are working on.

**Comment by Ahsankhalid618** [comment]
@iamleonie I am starting to work on writing test cases for jest to test this code.

**Comment by someshfengde** [comment]
@iamleonie  can i start working on converting Demo-text-search-plant from javascript to python ?

**Comment by iamleonie** [comment]
@someshfengde Yes, sounds great.

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
